# Generated by Django 4.1.1 on 2022-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taka', '0002_alter_balances_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='userName',
            field=models.CharField(max_length=50),
        ),
    ]
