# Generated by Django 4.1.1 on 2022-09-17 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taka', '0003_alter_balances_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balances',
            name='userName',
        ),
        migrations.AddField(
            model_name='balances',
            name='account_holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
