# Generated by Django 4.1.1 on 2022-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taka', '0006_alter_balances_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balances',
            name='account_holder',
        ),
        migrations.AddField(
            model_name='balances',
            name='userName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
